spring:
  application:
    name: spring-cloud-eureka-client

server:
  port: 8180

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
